### ISSUE TITLE
[BUG] Provide better handling of network errors

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotCpp#438]
**Description**
When connection to UTBot is not stable CLion shows unclear messages.

**To Reproduce**
1. Restart UTBot server with `utbot_server_restart.sh`
2. During restarting try to generate tests in CLion - as result unclear message shown
![image](https://user-images.githubusercontent.com/10035839/188834331-3aa733dd-10d1-42a7-8fa2-1850bae7c8c2.png)
3. When CLion client reconnected message `Project configured` shown
![image](https://user-images.githubusercontent.com/10035839/188836140-7a6320d6-8ea4-489f-a0a1-258fcab06091.png)

**Expected**
1. When connection lost - balloon with error appears which describes the problem
2. When connection lost - info balloon notifies that connection restored. 

**Errors in Client log console and idea.log**
```
10:28:40.0509 | Client.kt:177 [DefaultDispatcher-worker-2] |ERROR| Heartbeat failed with grpc io exception 
UNAVAILABLE: io exception 
10:28:40.0529 | Client.kt:177 [DefaultDispatcher-worker-6] |ERROR| Exception when executing server request 
UNAVAILABLE: io exception 
```

```
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - io.grpc.StatusException: UNAVAILABLE: io exception
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.Status.asException(Status.java:551)
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:295)
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
2022-09-07 10:18:04,928 [ 486068]   INFO - STDERR - 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - Caused by: java.net.SocketException: Connection reset
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
2022-09-07 10:18:04,929 [ 486069]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-09-07 10:18:04,930 [ 486070]   INFO - STDERR - 	... 1 more
```

**Comment by tyuldashev** [comment]
Though in VS code it's very similar, don't know if we need dedicated issue or use one for both plugins
![image](https://user-images.githubusercontent.com/10035839/188838058-ca46d723-2535-49c9-90ae-cda3af3c7f90.png)

@alexey-utkin how to better handle this?
